### ISSUE TITLE
OpenStack problem

### ISSUE THREAD

**Issue by ghost** [dianaclarke/openstack-notes#1]
First, let me say that I have been following your notes on the openstack install and they have helped me tremendously. I have ran into an issue and I was wondering if you can help me out or point me in the right direction. I am installing on Centos 7.3 and during the undercloud install I get the following error: error: invalid argument: could not find capabilities for arch=x86_64 domaintype=kvm. I have googled this but not found a definitive fix. Could you please assist? Thank you.

**Comment by dianaclarke** [comment]
@drjenn I don't work on OpenStack anymore. Good luck though!
